### ISSUE TITLE
Consider extracting the integration tests into their own module

### ISSUE THREAD

**Issue by metacosm** [dekorateio/dekorate#324]
This would help with actually testing the code since currently, since integration tests are within the module they test they have access to the code and therefore we're not really testing that the artifacts are properly generated. This is particularly important because it is very easy for maven shade plugin configuration to get out of sync and therefore generate wrong artifacts.
Also, the current architecture makes it very difficult to work with the integration tests from within an IDE and also make it impossible to skip (which we should be able to do).

**Comment by geoand** [comment]
I agree with this. Working on the integration tests withing IDEA is currently very difficult

**Comment by iocanel** [comment]
Even if extracted in their own module it still is going to be the same hurdle for most IDEs.
It's not the location that is causing issues, its the fact that we have to use maven invoker plugin.

**Comment by geoand** [comment]
In IDEA, there is also the extra pain that you need to explicitly mark certain directories as source  and test since the locations are not standard

**Comment by iocanel** [comment]
Again, that will not change by moving integration tests to its own module.

**Comment by geoand** [comment]
The idea I would say is not to place things in `it` under `src`, but use something more conventional like: https://github.com/quarkusio/quarkus/tree/master/integration-tests

**Comment by iocanel** [comment]
So, we are talking about completely ditching the `maven-invoker-plugin`.
I am ok with that.
The only downside to that is that we can't control build parameters without it, like: `-Ddekorate.build=true` which I don't think we use anyway.

**Comment by geoand** [comment]
I admit I wasn't aware of the intricacies that are being introduced due to the invoker plugin, but if it's something we can avoid, I would very much be in favor of that

**Comment by iocanel** [comment]
Let's ditch it.

**Comment by iocanel** [comment]
A tricky thing here would be releasing, as we would like to run integration tests during release, but not release the artifacts themselves. 

That needs some thought.

**Comment by geoand** [comment]
Good point

**Comment by geoand** [comment]
Perhaps something like:

```
    <build>
        <plugins>
            <plugin>
                <groupId>org.sonatype.plugins</groupId>
                <artifactId>nexus-staging-maven-plugin</artifactId>
                <configuration>
                    <skipNexusStagingDeployMojo>true</skipNexusStagingDeployMojo>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

or similar

**Comment by metacosm** [comment]
I actually would like to avoid running the integration tests while releasing… I understand why we might want to run them but I'd rather use CI for that and keep the release process as lightweight as possible.

**Comment by metacosm** [comment]
Another aspect to this problem is also the fact that issues with shaded jars are not currently detected / tested.

**Comment by geoand** [comment]
@iocanel can you give your take on this? I agree with @metacosm but you mentioned that the concerns we had may not be valid?

Also @gytis you mentioned your finding about the surefire plugin not being used? Can you elaborate?

**Comment by iocanel** [comment]
### On shaded artifacts

For each annotation module, we do have:

- a full jar
- a processors jar (because gradle is alergic to packaging everything neatly together)
- an annotations jar  (because gradle is alergic to packaging everything neatly together)
- a no processors jar ( = full - processors for quarkus or everyone else who just needs dekorate as a library).

We usually `test` that everything is fine by using the `processors` and `annotations` jars in the starters and thus the examples. And IMHO, that good enough.

### On reactor order

The most common reason a release might fail for me is an `invoker` test refering to artifact not build in the reactor.

Now in english: The most common reason a release might fail for me is an `invoker` test refering to `dekorate-spring-boot` from within a module built before spring boot (we do solve that by adding a test scoped dependency to `dekorate-spring-boot` in the owner module.

### On surefire plugin.
Dekorate integration tests can't just run with maven-surefire-plugin, we do need either normal modules that act as integration tests, or `maven-invoker-tests`. The later case requires either beanshell scripts or proper junit tests for validation/assertions. So, this is expected and its not really an issue.

#### More on invoker and surefire.
Speaking about `surefire` and `invoker`. From time to time we've seen sporadic failures due to `surefire` not behaving when called from within an `invoker` test. That manifests as random failures in CI. With tuning and SO we managed to limit those to an acceptable  degree, but the issue is still there. For me that alone is a good enough reason to proceed.

**Comment by iocanel** [comment]
Done.
