### ISSUE TITLE
@OpenshiftApplication livenessProbe/readinessProbe always uses default parameters

### ISSUE THREAD

**Issue by liborfuka** [dekorateio/dekorate#369]
It always uses default parameters even i set 
@OpenshiftApplication(expose=true, 
                         livenessProbe=@Probe(httpActionPath="/actuator/health",initialDelaySeconds=60,periodSeconds=3,timeoutSeconds=1),
                      readinessProbe=@Probe(httpActionPath="/actuator/health",initialDelaySeconds=10,periodSeconds=10,timeoutSeconds=1)).

More investigation: when i don't have spring-boot-actuator dependency in pom.xml it sets correct parameters. When i add spring-boot-actuator dependency to pom.xml it always uses defaults 0,30,10.

I used dekorate-core-0.8.2 for testing.

**Comment by iocanel** [comment]
Great catch! This is quite serious.

It seems that we have a conflict between two decorators, one added by the `OpenshiftHanlder` that handle the annotation and one added by the `SpringBootApplicationHandler`. 

The issue here is that in both cases a configurator should be used instead and the configuration provided by each should be merged.
