### ISSUE TITLE
Support for resource level annotations

### ISSUE THREAD

**Issue by kameshsampath** [dekorateio/dekorate#553]
It will be good to have resource level annotations configurable via properties. E.g. let us say we have a `dekorate.kubernetes.expose=true`, then doing something like 

```
dekorate.kubernetes.expose.annnotations[0].key=foo
dekorate.kubernetes.expose.annnotations[0].value=bar
```

Should add the annotations to expose related resources such as *ingress*

**Comment by iocanel** [comment]
I would prefer if we used `ingress` instead of `expose` unless these annotations are also applicable to Route too.

Also, do you think that we should expose the annotation itself or a property describes the intent, e.g. `dekorate.kubernetes.ingress.rewrite-target`?

**Comment by kameshsampath** [comment]
@iocanel , I initially thought about using specific k8s resource kind, then wondering if we are complicating :( .. so thought to make it general as annotations.

**Comment by kameshsampath** [comment]
>Also, do you think that we should expose the annotation itself or a property describes the intent, e.g. dekorate.kubernetes.ingress.rewrite-target?

That sounds like a good idea too

**Comment by iocanel** [comment]
I have been pondering for a solution around this and TBH, I haven't been able to find an elegant technical soluton.

The best thing that pops to my mind, is to modify @Label and @Annotation in order to include a field say `resourceKinds`.

This way one could 

```java
@KubernetesApplication(name="myapp", labels=@Label(name="foo", value="bar", rerourceKinds=["Service", "Ingress"])
```

or in properties;

```
dekorate.kubernetes.labels[0].key=foo
dekorate.kubernetes.labels[0].value=bar
dekorate.kubernetes.labels[0].resource-kinds=Service,Ingress
```

I  think that this is pretty close to what @kameshsampath needs and it should also be compatible with what have in downstream projects. @geoand wdyt?

**Comment by geoand** [comment]
I like the idea!
