### ISSUE TITLE
jaxrs support should not be coupled with thorntail.

### ISSUE THREAD

**Issue by iocanel** [dekorateio/dekorate#597]
I think that we should have an independant jaxrs module that would be then used by the thorntail extension.

**Comment by iocanel** [comment]
cc @Ladicek

**Comment by Ladicek** [comment]
I do remember adding Thorntail support to Dekorate, and to autodetect if something is exposed over HTTP, it looks for JAX-RS and Servlet annotations. That's all there is, AFAIK.

Frankly, I'm not even sure someone uses Dekorate with Thorntail, since we've always promoted the Fabric8 Maven plugin, and considering Thorntail end of life, we probably won't even be switching to JKube. So removing Thorntail support from Dekorate is certainly a possibility.
