### ISSUE TITLE
Add support for subresources

### ISSUE THREAD

**Issue by goldmann** [dekorateio/dekorate#676]
It would be great to have support for subresources in generated CRD's: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#subresources.

This would allow for maintaining resources that require statuses.

**Comment by iocanel** [comment]
When I was working on: https://github.com/dekorateio/dekorate/pull/209 I was banging my head on how we could add the statuses on the model class. I think that subresources answers that .I

I'll try to have a look asap.

**Comment by iocanel** [comment]
@goldmann I created an early draft of how subresources integration could look like.


However, I am thinking that this can be further improved by going `full on annotations`. This would mean that instead of passing the `status` class as a parameter we could possibly have a `@Status` annotations instead. 

The same approach could possibly work for scale, too. Instead of passing the paths by hand. Maybe we could have annotations. Especially for scaling this would be awesome as it would prevent the user from passing the wrong path, etc.

**Comment by iocanel** [comment]
@metacosm: cc your feedback is more than welcome here.

**Comment by metacosm** [comment]
Will take a look ASAP.
