### ISSUE TITLE
Property configuration always overwrites values for primitive properties

### ISSUE THREAD

**Issue by iocanel** [dekorateio/dekorate#706]
The problem seems to be that the generated config objects, are generated with default values.
That works when they represent annotation configuration, but they do 'taint' the property configuration.

This leads to isses when it comes to merging of configs that include primitives.
For example setting the number of replicas via annotations, will be ignored if any property configuration is found, even if its irrelevant to replicas.

**Comment by aureamunoz** [comment]
After spend a little time on this, yes the problem is that [we are always returning the value from the `higher priority configuration`](https://github.com/dekorateio/dekorate/blob/a958a8bb7c032b0e6ac15e5cf08426943c78a4c6/core/src/main/java/io/dekorate/utils/Beans.java#L77) in case of primitives or enums. I don't find the way to detect which is the conf that has been setted by user so what should we do? document clairly this case? Do you have an idea @iocanel ?
